#!/usr/bin/env node

/**
* Goes over each element dir and merges the `assets` dir (if any)
* to `build/assets`
*/

const path = require('path');
const fs = require('fs-extra');
const elDir = path.resolve(__dirname, '../src/elements');
const targetDir = path.resolve(__dirname, '../build/assets');

fs.ensureDirSync(targetDir)

// get all element directories
const elsDirContents = fs.readdirSync(elDir)
let elDirs = [];
elsDirContents.forEach(function(c){
  const filePath = `${elDir}/${c}`
  stat = fs.statSync(filePath);
  if (stat.isDirectory()){
    elDirs.push(filePath);
  }
})

// look into each directory and copy `assets` dir if it exists
elDirs.forEach(function(dir){
  const elDirContents = fs.readdirSync(dir)
  if (elDirContents.indexOf('assets') >= 0 ){
    fs.copySync(`${dir}/assets`, targetDir);
  }
})

process.exit()