#!/usr/bin/env node

// taken from https://github.com/home-assistant/home-assistant-polymer/blob/master/script/minify.js
const minify = require('html-minifier');
const fs = require('fs');

const html = fs.readFileSync('build/cockpit-asq.vulcanized.html').toString();

const minifiedHtml = minify.minify(html, {
  customAttrAssign: [/\$=/],
  removeComments: true,
  removeCommentsFromCDATA: true,
  removeCDATASectionsFromCDATA: true,
  collapseWhitespace: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  minifyJS: true,
  minifyCSS: true
});

fs.writeFileSync('build/cockpit-asq.html', minifiedHtml);